### ISSUE TITLE
خطای خصوصیت SelectedDate

### ISSUE THREAD

**Issue by GhalamborM** [VahidN/Silverlight-Persian-DatePicker#1]
# Summary of the issue
سلام
تو نسخه wpf
یه تاریخ انتخاب میکنیم
 تاریخ رو پاک میکنیم
خصوصیت SelectedPersianDate  مقدار نداره
اما خصوصیت SelectedDate مقدار قبلی رو نشون میده
که نباید نشون بده

و اینکه بهتر نیست نوع برگشتی خصوصیت SelectedDate 
بجای string
datetime باشه

## Environment

 Visual Studio 2017
.net framework 4.7.1

**Comment by VahidN** [comment]
<div dir="rtl">

[امكان تنظيم مقادير نال هم اضافه شد](https://github.com/VahidN/Silverlight-Persian-DatePicker/commit/45051f052cb5a309c4439c585437eae1cb9ce7d1)
